server:
  port: 8081
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8061.com:8061/eureka
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#    prefix: classpath:/templates/
feign:
  hystrix:
    enable: true