server:
  port: 8071
mybatis:
  type-aliases-package: jf.pojo
  mapper-locations: classpath:mapper/**/*.xml
spring:
  application:
    name: comeback-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/kd_cs
    username: root
    password: 18344539135
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  instance:
    instance-id: comebackService8071
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8061.com:8061/eureka/
